### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by Myqilixiang** [WICG/virtual-scroller#168]
how to import source,can i user npm install or <script src="***">,thanks

**Comment by domenic** [comment]
Heya. This is a repository for a proposal for web standards. The README outlines how to use it, see e.g. https://github.com/WICG/virtual-scroller#sample-code, but it currently is only implemented behind a flag in Chrome. So to test it out, use [Chrome Canary](https://www.google.com/chrome/canary/), and turn on the Experimental Web Platform Features flag (see e.g. [this article](http://christopher.org/setting-chrome-flags-for-experimental-web-browser-layout-features/)).

I hope this helps! I'll close the issue since it's not an issue with the spec, so we don't need to track it, but we're happy to continue discussing in the closed thread.
