### ISSUE TITLE
Approx. release date?

### ISSUE THREAD

**Issue by innerop** [WICG/virtual-scroller#196]
Hello,

Per the docs, this currently requires a command line flag.

Do you have an approximate release/GA date?

Cheers

**Comment by chrishtr** [comment]
At this time there is no plan to ship a virtual-scroller element built into the platform. Instead, we're focusing on shipping the [necessary primitives](https://github.com/WICG/display-locking) and a user-space [virtual-scroller library](https://github.com/flackr/virtual-scroller) ([demo here](https://flackr.github.io/virtual-scroller/demo/index.html)).

**Comment by innerop** [comment]
Ok, thank you for this info.

**Comment by acusti** [comment]
@chrishtr checking in on this one year later: is your summary still accurate? seems like the user-space flackr/virtual-scroller library hasn’t had any updates since april. also, the README in that repo suggests that it’s actually a built-in module:
```html
<!--
  virtual-scroller lives in a built-in module and needs to be imported before use.
  (The name of the module is subject to change.)
-->
<script type="module">
import "std:virtual-scroller";
</script>
```

sorry if this is the wrong place to ask about this. i would’ve created or commented on an issue in the other repo, but issues are turned off there.

**Comment by jogibear9988** [comment]
look here: https://github.com/WICG/virtual-scroller/issues/201 the prototype has been deleted

**Comment by chrishtr** [comment]
It's still accurate. We are not working on a built-in virtual scroller. Instead we shipped the content-visibility CSS property, which can be used as a primitive to buildone.
