### ISSUE TITLE
not working with LitElements

### ISSUE THREAD

**Issue by hari2m** [WICG/virtual-scroller#199]
Hi I am trying to get it working with a lit-html project and the virtual-scroller does not work. The data just overflows and takes so much time to render 2000 records with 40 columns.

Below is the code that I was using.

    import { LitElement, html } from 'lit-element/lit-element';
    import 'virtual-scroller/index.commonjs';

    export class DevGrid extends LitElement {
    static get is() {
        return `div-grid`;
    }

    static get properties() {
        return {
            columns: { type: Array },
            data: { type: Array }
        };
    }

    render() {
        let { columns, data } = this;
        return html`
        <virtual-scroller id="scroller" style="display:block;height:300px;width:300px;">
            ${data ?
            html`${data.map((value) => 
                html`<div style="display:block">
                        ${columns ? html`${columns.map((column)=>
                            html`${value[column]}`)}`
                            : html``}
                    </div>`)}`
            : html``}
        </virtual-scroller>
        `;
        }
    }

    customElements.define(DevGrid.is, DevGrid);

Was it me or the scroller is not working with lit-html?

**Comment by fergald** [comment]
Please file chrome bugs on http://crbug.com/ (I'm assuming you're using chrome) but real-quick, virtual-scroller should be entirely transparent. When you say "render", if you mean it takes a lot of time to create the elements then this is expected, virtual-scroller has no impact on the time spent in JS creating the elements. If on the other hand you're saying that the rendering is (the actual work done by chrome's rendering engine) then that's a problem. Please use chrome's performance tracing in the dev tools and see if the problem is "scripting" or "rendering",

**Comment by fergald** [comment]
Also replace `<virtual-scroller>` with `<div>` in your sample and see what's the difference. You should see that the div version costs a lots more rendering than the virtual-scroller version. If you don't, that's a useful data-point.

**Comment by elf-pavlik** [comment]
@hari2m possibly your issue doesn't relate to `<virtual-scroller>` you may find some useful tips on improving performance in this lit-html presentation by Justin Fagnani
*The Virtue of Laziness: Leveraging Incrementality for Faster Web UI (Chrome Dev Summit 2018)* https://youtu.be/ypPRdtjGooc

Adding `await new Promise(resolve => setTimeout(resolve))` worked like a charm in one of my projects.
